"""cascade deleting models added

Revision ID: 7ad24f125214
Revises: 23f31e30d3b0
Create Date: 2025-04-29 14:36:11.749944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad24f125214'
down_revision: Union[str, None] = '23f31e30d3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('expenses_user_id_fkey', 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key('expenses_user_id_fkey', 'expenses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
